// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUv3Uzxf_wznj86m5Tr6nE69vvhaQS81E',
    appId: '1:379594630154:web:aafdc555664490d7466bf3',
    messagingSenderId: '379594630154',
    projectId: 'tasktrackingapp-5bac3',
    authDomain: 'tasktrackingapp-5bac3.firebaseapp.com',
    storageBucket: 'tasktrackingapp-5bac3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2PvH1gvYsntHpcHpOc7I39mE_8d0Eg5A',
    appId: '1:379594630154:android:72f89ed7a5ee90f8466bf3',
    messagingSenderId: '379594630154',
    projectId: 'tasktrackingapp-5bac3',
    storageBucket: 'tasktrackingapp-5bac3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMsGSwzQcoueGWBLcX5UwvRoT0LUrY254',
    appId: '1:379594630154:ios:1d574cf12db32249466bf3',
    messagingSenderId: '379594630154',
    projectId: 'tasktrackingapp-5bac3',
    storageBucket: 'tasktrackingapp-5bac3.firebasestorage.app',
    iosBundleId: 'com.example.tasktrackerApp',
  );
}
